# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaterEnvironment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QMessageBox, QApplication
from utility.guet_judge import GuetJudge


class WaterEnvironment(QtWidgets.QMainWindow):
    we_signal = pyqtSignal(object)

    def __init__(self, parent=None):
        super(WaterEnvironment, self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 359)
        MainWindow.setMinimumSize(QtCore.QSize(359, 358))
        MainWindow.setMaximumSize(QtCore.QSize(359, 359))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(146, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.InputEvent)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "水环境版块"))
        self.label.setText(_translate("MainWindow", "PH："))
        self.label_2.setText(_translate("MainWindow", "悬浮物（mg/L）："))
        self.label_3.setText(_translate("MainWindow", "活性磷酸盐（μg/L）:"))
        self.label_4.setText(_translate("MainWindow", "无机氮（μg/L）："))
        self.pushButton.setText(_translate("MainWindow", "输入"))

    def InputEvent(self):
        result = QMessageBox.question(self, "注意", "您确定好输入的参数了吗",
                                      QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        ph = self.lineEdit.text()  # PH
        solids = self.lineEdit_2.text()  # 悬浮物
        phosphate = self.lineEdit_3.text()  # 活性磷酸盐
        nitrogen = self.lineEdit_4.text()  # 无机氮
        b = True
        if result == QMessageBox.Yes:
            if ((len(ph) == 0) or (len(solids) == 0) or (len(phosphate) == 0) or (len(nitrogen) == 0)):
                b = False
                QMessageBox.critical(self, "错误", "无法进行珊瑚礁健康评价，缺少水环境版块参数")
            else:
                # 判断是否输入的都是数字
                if (GuetJudge.is_number(ph) and GuetJudge.is_number(solids) and GuetJudge.is_number(phosphate) and GuetJudge.is_number(nitrogen)):
                    QMessageBox.information(self, "通知", "成功输入数据")
                    ph = float(ph)
                    solids = float(solids)
                    phosphate = float(phosphate)
                    nitrogen = float(nitrogen)
                    self.close()
                else:
                    QMessageBox.critical(self, "错误", "请输入正确类型的参数")
            we = WE(ph, solids, phosphate, nitrogen, b)
            self.we_signal.emit(we)
        elif result == QMessageBox.No:
            pass


    def evaluate(self):
        ph = float(self.lineEdit.text())  # PH
        solids = float(self.lineEdit_2.text())  # 悬浮物
        phosphate = float(self.lineEdit_3.text())  # 活性磷酸盐
        nitrogen = float(self.lineEdit_4.text())  # 无机氮
        ph_score = 5 if ((ph <= 7.0) or (ph > 9.0)) else (10 if ((7.0 < ph < 7.5) or (8.5 < ph < 9.0)) else 15)
        solids_score = 5 if (solids > 6) else (10 if (3 < solids < 6) else 15)
        phosphate_score = 5 if (phosphate > 30) else (10 if (15 < phosphate < 30) else 15)
        nitrogen_score = 5 if (nitrogen > 300) else (10 if (200 < nitrogen < 300) else 15)
        we_score = ph_score + solids_score + phosphate_score + nitrogen_score
        return we_score/4


class WE:
    def __init__(self, ph, solids, phosphate, nitrogen, b):
        self.ph = ph
        self.solids = solids
        self.phosphate = phosphate
        self.nitrogen = nitrogen
        self.b = b

